.gitignore
Dockerfile
README.md
config/default.js
package-lock.json
package.json
server.js
src/client/api/secret.js
src/client/api/upload.js
src/client/routes/account/index.js
src/client/routes/api-docs/index.js
src/client/routes/home/index.js
src/client/routes/secret/index.js
src/server/controllers/secret.js
src/server/controllers/upload.js
src/server/helpers/crypto.js
src/server/services/do.js
src/server/services/redis.js

This PR will make it possible for logged-in users to attach an image to the secret text. The attached image will be encrypted the same way the text is.

feat: upload attachment

---

src/client/components/form/style.module.css
src/client/components/form/textarea.js
src/client/routes/home/index.js

Removing this as it is just bad UX

Fix: remove the expansion of the textarea

---

CONTRIBUTION.md
README.md

https://github.com/HemmeligOrg/Hemmelig.app/issues/34

chore: add contribution file

---

src/server/helpers/password.js

https://github.com/HemmeligOrg/Hemmelig.app/issues/36

chore: increase the salt rounds for more secure hashing

---

config/default.js
src/server/decorators/allowed-ip.js
src/server/decorators/rate-limit.js
src/server/helpers/client-ip.js

This array should be updated with allowed headers based on peoples needs. However, be careful.
This PR will partially solve this issue: https://github.com/HemmeligOrg/Hemmelig.app/issues/38

feat: get client ip from header set in checkHeaders array

---

.github/workflows/owasp_zap.yaml

Update this later to run on the fly for PRs

security: run the DAST for every push to main

---

public/locales/en/translation.json
public/locales/es/translation.json
src/client/routes/home/index.js

This commit has new strings moved from the code into the English json and also the Spanish file.

Spanish translation

---

README.md

https://github.com/HemmeligOrg/Hemmelig.app/issues/110

docs: #110 Add contributors badge to the README

---

src/client/routes/account/index.js
src/server/controllers/account.js

This PR adds the confirm password field and checks if the new password and confirm password is equal then only update the field.
This closes #116

:zap: added confirm password field

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/other.yml

Added issue template in the project.

feat: added issue template

---

cli.js
hemmelig.ts
package.json
src/client/app.js
src/client/routes/home/index.js
src/client/routes/secret/index.js

the application will still support use url params for a while, but will be removed at the 5.0 breaking release

feat: change the application to use url hash for the encryption key

---

src/client/components/header/index.jsx
src/client/helpers/cookie.js
src/server/controllers/authentication.js

one is for information for the frontend, and the other for the jwt validation

feat: use a public and sacred cookie

---

public/locales/en/translation.json
server.js
src/client/api/users.js
src/client/routes/account/index.jsx
src/client/routes/account/users.jsx
src/server/controllers/admin/users.js
src/server/controllers/authentication.js
src/server/prehandlers/read-only.js

When this PR is merged and released, it is possible to set hemmelig to read only mode, which allows only admins and creators to create secrets. Everyone else has just read rights. https://github.com/HemmeligOrg/Hemmelig.app/issues/154

feat: add initial user management tab

---

package-lock.json
package.json
src/client/admin-shell.jsx
src/client/app-shell.jsx
src/client/components/quill/index.jsx
src/client/index.css
src/client/routes/home/index.jsx
src/client/routes/secret/index.jsx

This will support inline images (gifs) and formatting

feat: add react quill

---

README.md

This PR adds information about setting the correct permissions/ownership for the volumes directories.

Add info about volumes permissions

---

src/client/routes/home/index.jsx
src/client/routes/secret/index.jsx
src/shared/helpers/crypto.js

Meaning when the password is set, it will be used to decrypt the message. The password will not be part of the key set in the URL at all.
This also means the secret is no longer just protected by a password check.
1. The password will block access to fetch the secret if is incorrect
2. The password will be part of the encryption and decryption key, but it is not set as a fragment in the URL

feat: use password as part of the encryption key

---

src/client/routes/home/index.jsx
src/client/routes/home/style.module.css

fixes #233 
Added a remove button in selected file Badge component

feat: added remove button for selected files

---

README.md
config/default.cjs
src/client/routes/home/index.jsx
src/server/decorators/user-features.js

On a side note here. Man, I really have to clean up this repository. Bloated spaghetti.

feat: allow file upload without login if env flag SECRET_UPLOAD_RESTRICTION  is set to false

---

public/locales/de/translation.json

Translated the missing strings and fixed some of the existing ones.
Also changed the order of some items so it matches the original, English one.

Updated german translation

---

src/client/routes/signin/index.jsx

Added autofocus for username upon sign in

Added autofocus for username

---

src/client/api/authentication.js
src/client/app-shell.jsx
src/client/components/header/index.jsx
src/client/components/quill/index.jsx
src/client/helpers/cookie.js
src/client/routes/signin/index.jsx
src/server/controllers/authentication.js
src/server/decorators/allowed-ip.js

feat: refresh session

---

README.md
prisma/migrations/20240127131057_public_secret/migration.sql
prisma/migrations/20240127142307_ip_public_secrets/migration.sql
prisma/schema.prisma
public/locales/en/translation.json
src/client/api/secret.js
src/client/components/header/nav.jsx
src/client/routes.jsx
src/client/routes/home/index.jsx
src/client/routes/public/index.jsx
src/client/routes/secret/index.jsx
src/server/controllers/secret.js
src/server/decorators/attachment-upload.js

These will not be encrypted, and available for everyone under the route /public. File uploads not allowed. The IP address will be recorded to the public secret creation.

feat: add public secrets

---

public/locales/it/translation.json

I have added italian translation in the directory `locales`. Maybe I will add more strings to be translated because there are others strings not translatable.

Added italian translation

---

public/locales/de/translation.json

Hey, I just deployed Hemmelig on my own server and noticed some of the german translations were missing.
I added all the ones present in the english translation.json file and made sure to keep them in the same order.

Update german translation.json

---

public/locales/en/translation.json
public/locales/it/translation.json
src/client/app-shell.jsx
src/client/components/header/nav.jsx
src/client/components/settings/main-links.jsx
src/client/components/settings/secondary-links.jsx
src/client/components/spinner/index.jsx
src/client/routes/account/account.jsx
src/client/routes/account/index.jsx
src/client/routes/account/secrets.jsx
src/client/routes/account/settings.jsx
src/client/routes/account/users.jsx
src/client/routes/privacy/index.jsx
src/client/routes/signin/index.jsx
src/client/routes/signout/index.jsx
src/client/routes/signup/index.jsx
src/client/routes/terms/index.jsx

I have added i18n to all strings, except for terms&conditions and privacy. I have already translated them in italian, so for the other languages the person that will translate Hemmelig should compare the last english version of JSON translation. Do you have plan to move these pages in indipendent files? I think that adding these texts in JSON file for translation couldn't be the right choice.

Added i18n to almost all strings

---

package-lock.json
package.json
src/client/api/authentication.js
src/server/controllers/admin/settings.js
src/server/prehandlers/restrict-organization-email.js
src/shared/helpers/get-email-domain.js

This pull request includes changes primarily aimed at refactoring the way email domains are extracted and handled, and improving error messaging in the authentication process. The `extract-domain` package was removed and replaced with a custom `getEmailDomain` function, which is now used in multiple files. Additionally, the error messaging in the `signIn` and `signUp` functions was changed from `json.error` to `json.message`.
Refactoring email domain extraction:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L54): Removed the `extract-domain` package.
* [`src/shared/helpers/get-email-domain.js`](diffhunk://#diff-e9bde2d378f59f619da857f3685ddb43e23a4273afae49472a152a489e653c2aR1-R10): Added a new function `getEmailDomain` for extracting …

fix: get email domain in a simplified way

---

public/locales/sl/translation.json

Added Slovenian translation for Hemmelig. Looking forward for version that will have it included. Thank you.

Added slovenian Translation

---

docker-compose.yml

Updated version tag no. for docker-compose.yml

Updated version tag no. for docker-compose.yml

---

server/controllers/authentication.js

The issue do not occur in dev mode, which makes it hard to debug.

fix: try to remove the httponly cookie by setting it as expired

---

public/locales/fr/translation.json

Hello,
Thanks for your app !
I saw that the French translations were incomplete so i have updated them. I tried to keep them user frendly.
Please tell me if you want any changes to my PR.
Regards,
Elian for Tetras Libre.

Complete French translation

---

server/prehandlers/disable-users.js

Attempts to fix https://github.com/HemmeligOrg/Hemmelig.app/issues/317

fix: return 403 on authy endpoints when user disabled

---

.gitignore
Dockerfile
client/components/header/index.jsx
client/components/header/nav.jsx
client/components/quill/index.jsx
client/routes/account/settings.jsx
client/routes/api-docs/index.jsx
client/routes/home/index.jsx
client/stores/settingsStore.js
prisma/migrations/20250115144641_hide_allowed_ip/migration.sql
prisma/schema.prisma
public/locales/de/translation.json
public/locales/en/translation.json
server/controllers/admin/settings.js

Hi, I recently modified your application a bit for our own environment.
I added a few tweaks that I want to contribute back to the main repo:
- Hide the signup button if disabled in settings (https://github.com/HemmeligOrg/Hemmelig.app/issues/297)
- Remove unused code
- Hide `max_views` input when `preventBurn` is set
- Add a settings entry to hide IP restriction - could be useful to simplify the secret creation
- fix some syntax in the Dockerfile and reduce image size
- fix the editor to not disappear after change
I am not too familiar with the authentication scheme, but I would suggest not to show the complete instance settings to a not logged in user. Probably it would be to think about an authenticated get endpoint for settings entries like restricted_email_domains

UI improvements

---

client/routes/home/index.jsx

this will simplify the flow of creating a secret

feat: collapse security form by default

---

client/routes/home/index.jsx

This pull request includes changes to the `client/routes/home/index.jsx` file to improve the styling and responsiveness of the `ErrorBanner` and `FormSection` components. The most important changes include removing unnecessary background elements and updating styles to be responsive.
Styling improvements:
* [`client/routes/home/index.jsx`](diffhunk://#diff-b33bc750b2b51c1ae0a092217b95456345e45b33c01922429b4b936efab2cc7fL600): Removed the background noise image from the `ErrorBanner` component to simplify the design.
* [`client/routes/home/index.jsx`](diffhunk://#diff-b33bc750b2b51c1ae0a092217b95456345e45b33c01922429b4b936efab2cc7fL682-R685): Updated the `FormSection` component to use responsive styles for background gradients, borders, and padding, and removed the background noise image …

chore: minor layout adjustments

---

client/admin-shell.jsx
client/app-shell.jsx
client/config/default.js
vite.config.js

Fixes: https://github.com/HemmeligOrg/Hemmelig.app/issues/328

chore: set the git tag version and sha

---

client/routes/home/index.jsx
config/default.cjs
public/locales/en/translation.json
server/controllers/secret.js

This pull request includes several changes aimed at improving form validation, UI feedback, and configuration management. The most important changes include adding a new validation function to check for empty text inputs, updating the UI to provide feedback when the text input is empty, removing an unused configuration key, and enhancing the server-side validation for the `text` field.
* [`client/routes/home/index.jsx`](diffhunk://#diff-b33bc750b2b51c1ae0a092217b95456345e45b33c01922429b4b936efab2cc7fR148-R149): Added a new function `isTextEmpty` to check if the text input is empty and updated the submit button to disable it and show a tooltip when the text is empty. [[1]](diffhunk://#diff-b33bc750b2b51c1ae0a092217b95456345e45b33c01922429b4b936efab2cc7fR148-R149) …

chore: cleanup

---

public/locales/de/translation.json

chore: update german translation

---

client/routes/home/index.jsx
client/stores/secretStore.js
public/locales/en/translation.json

1. Move the file upload to under the title
2. Create new components for certain security settings
3. Restructure the security settings

feat: new structure of the UI

---

client/routes/home/index.jsx

have to be verified on linux or a windows computer

fix: the dropdown bg

---

server/controllers/secret.js

This commit modifies the `getSecretRoute` function to use Prisma's transaction API, ensuring atomicity for read and delete operations.
The changes involve:
- Wrapping all database operations within a `prisma.$transaction` block.
- Using the transaction context (`tx`) for all database operations.
- Ensuring that the read, view count update, and potential deletion happen atomically.
- Maintaining the same business logic while preventing race conditions.
This addresses the race condition by:
- Using database-level transactions to guarantee atomicity.
- Preventing other requests from reading the same secret between the read and potential delete operations.
- Preserving all existing functionality (password checking, view counting, etc.) within the transaction.
The transaction ensures that if …

feat(secrets): Ensure atomic read and delete operations for secrets
